name: CI

on: [pull_request]

jobs:
  linked_issue:
    name: Jira
    runs-on: ubuntu-latest
    steps:
    - uses: openstax/jira-linked-action@v0.1.14
      with:
        jira_site: openstax
        jira_project: DISCO
        jira_email: ${{ secrets.JiraEmail }}
        jira_token: ${{ secrets.JiraToken }}
  test:
    name: checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [lambda, frontend, orn-locator]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn install --immutable
    - run: yarn build
    - run: yarn ci
      working-directory: packages/${{ matrix.module }}
