name: CI

on: [pull_request]

jobs:
  test:
    name: checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [lambda, frontend]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn install --immutable
    - run: yarn build
    - run: yarn ci
      working-directory: packages/${{ matrix.module }}
