name: CI

on: [pull_request]

jobs:
  test:
    name: checks
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: ./scripts/ci.bash
