name: Lint

on: [pull_request]

jobs:
  cfn:
    timeout-minutes: 30
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run pip install
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint **/*.cfn.yml
  spelling:
    name: spelling
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn install --immutable
    - run: yarn ci:spelling
  syncpack:
    name: versions
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn install --immutable
    - run: yarn ci:versions
