name: CI

on: [pull_request]

jobs:
  test:
    name: spelling
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn install --immutable
    - run: yarn ci:spelling
